apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      api: grafana
  template:
    metadata:
      labels:
        api: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: grafana-secrets
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
              subPath: prometheus.yml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/json
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
