apiVersion: v1
kind: Service

metadata:
  name: products-service
  namespace: marketplace

spec:
  type: ClusterIP
  selector:
    api: products-service
  ports:
    - port: 80
      targetPort: 3001
