apiVersion: apps/v1
kind: Deployment

metadata:
  name: payments-service
  namespace: marketplace
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      api: payments-service
  template:
    metadata:
      labels:
        api: payments-service
    spec:
      containers:
        - name: payments-service
          image: payments-service:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: payments-service
            - secretRef:
                name: payments-service-secrets
            - secretRef:
                name: jwt-secret
          ports:
            - containerPort: 3004
          startupProbe:
            httpGet:
              path: /health
              port: 3004
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 192Mi
