apiVersion: v1
kind: ConfigMap

metadata:
  name: checkout-service
  namespace: marketplace
data:
  PORT: "3003"
  NODE_ENV: production
  DB_HOST: host.docker.internal
  DB_PORT: "5436"
  DB_USERNAME: postgres
  DB_DATABASE: checkout_db
  JWT_EXPIRES_IN: 24h
  RABBITMQ_QUEUE_PAYMENTS: payment-queue
  RABBITMQ_EXCHANGE: payments
  USERS_SERVICE_URL: http://users-service
  PRODUCTS_SERVICE_URL: http://products-service
  PAYMENTS_SERVICE_URL: http://payments-service
