apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: checkout-service-hpa
  namespace: marketplace

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkout-service

  minReplicas: 3
  maxReplicas: 8

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Pods
          value: 2
          periodSeconds: 5
