apiVersion: v1
kind: Secret

metadata:
  name: checkout-service-secrets
  namespace: marketplace
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluQGhvc3QuZG9ja2VyLmludGVybmFsOjU2NzI=
